### ISSUE TITLE
Server crashes using dolly on containers

### ISSUE THREAD

**Issue by esotericist** [AnimeniacYuuto/InventoryTools#1]
InventoryTools-1.7.10-1.0.1.jar
YuutoLib-1.7.10-1.0.2.jar
forge-1.7.10-10.13.4.1448-1.7.10-universal.jar

Attempting to pick up an Enhanced Inventories cabinet yielded the below listed crash.
After bringing the server back up, I was then able to place it back down without trouble, then pick up and place a jabba barrel without error.
The last test I made before submitting this was picking up a Storage Drawers drawer, which was picked up fine, but the server crashed on placing it down.
This is the point where I decided to stop sciencing.

Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.func_70614_a(DF)Lnet/minecraft/util/MovingObjectPosition;
        at yuuto.inventorytools.items.ItemDolly.func_77659_a(ItemDolly.scala:78)
        at net.minecraft.item.ItemStack.func_77957_a(Unknown Source)
        at net.minecraft.server.management.ItemInWorldManager.func_73085_a(Unknown Source)
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539)
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by AnimeniacYuuto** [comment]
should be fixed with edd90fdc5173c5693c67139467ada1335d90f7df and 2b63774f18cf3fc93a414c95f1f9b62955b01314

**Comment by esotericist** [comment]
It might be a good idea to wait to close issues like this at least until you've gotten a release out which no longer has the problem. Makes it much less likely you'll receive duplicate reports between the time you've found a solution and when a build is available to users, since closed issues aren't immediately visible to someone looking to report a problem.

**Comment by AnimeniacYuuto** [comment]
just pushed out the release which is now available on curse, and before i closed the issue the releases section of the repo

**Comment by esotericist** [comment]
Yeah, I realized that just a moment ago. It looks like the release just took its sweet time to be available.
I'll get this new build in place and test it right away. Thanks for the responsiveness!

**Comment by AnimeniacYuuto** [comment]
no problem, thanks for the advice, i like constructive criticism it is also so hard to find :/

**Comment by esotericist** [comment]
I just try not to think about the nonconstructive elements of the community, and focus on things like awesome golden dollies. :D

More on-topic: Fix works, able to pick up/place all relevant objects without trouble, and now I've gotten to play with the awesome transfer mode.
Thank you again!
